services:
    mysql:
            image: mysql:5.7
            container_name: mysql-database
            tty: true
            ports:
                - "4208:3306"
            environment:
                MYSQL_ROOT_PASSWORD: 1234
                MYSQL_DATABASE: actividadartesanal_2024
                MYSQL_USER: admin
                MYSQL_PASSWORD: 1234
    
    phpmyadmin:
            image: phpmyadmin
            container_name: phpmyadmin-database
            ports:
                - "4283:80"
            environment:
                PMA_HOST: mysql-database
                MYSQL_ROOT_PASSWORD: 1234
            depends_on:
                - mysql
                